---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    type: database
spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    type: database
...
