---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  labels:
    tomcat: appserver
spec:
  replicas: 2
  selector:
    matchLabels:
       tomcat: appserver
  template:
    metadata:
      name: tomcat-pod
      labels:
        tomcat: appserver
    spec:
      containers:
        - name: tommy
          image: tomee
          ports:
            - containerPort: 8080
              hostPort: 8989
...



