---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  labels:
    type: appserver
spec:
  selector:
    matchLabels:
      type: appserver
  replicas: 1
  template:
    metadata:
      name: tomcat-pod
      labels:
        type: appserver
    spec:
      containers:
        - name: appserver
          image: tomee
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels:
    type: appserver
spec:
  ports:
    - port: 8080
  selector:
    type: appserver
...
