---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    type: proxy
spec: 
  containers:
    - name: mynginx
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8080
    - name: mytomee
      image: tomee
      ports: 
        - containerPort: 8080
          hostPort: 8081
...
