---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  type: NodePort
  selector:
    tomcat: appserver
  ports:
  - name: tomee
    port: 8080
    targetPort: 8080
    nodePort: 30080
...
